# Generated by Django 5.2.17 on 2026-10-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="reminded_at",
            field=models.DateTimeField(
                blank=True,
                help_text="زمان پیامک یادآوری سبد رهاشده.",
                null=True,
                verbose_name="یادآوری پیامکی",
            ),
        ),
    ]
