"""Generate ``static/admin_theme/unfold-rtl.css`` from the installed django-unfold stylesheet.

Unfold sets ``<html dir="rtl">`` for Persian (Django's ``LANGUAGE_BIDI``), and flexbox/grids flip by
themselves, but its Tailwind build still contains physical utilities (``ml-*``, ``pl-*``,
``left-*``, ``text-left``, ``border-l``, ``rounded-l``, ``translate-x``…). This command mirrors
every such utility under ``[dir=rtl]``. Rerun it after upgrading django-unfold:

    python manage.py build_admin_rtl_css
"""

import re
from importlib.metadata import version
from pathlib import Path

import unfold
from django.conf import settings
from django.core.management.base import BaseCommand

SWAP_PROPS = {
    "margin-left": "margin-right",
    "padding-left": "padding-right",
    "left": "right",
    "border-left-width": "border-right-width",
    "border-left-style": "border-right-style",
    "border-left-color": "border-right-color",
    "border-top-left-radius": "border-top-right-radius",
    "border-bottom-left-radius": "border-bottom-right-radius",
}
SWAP_PROPS.update({v: k for k, v in SWAP_PROPS.items()})
_DECL_RE = re.compile(r"([a-z-]+)\s*:\s*([^;]+)")


def _reset_value(prop: str) -> str | None:
    if prop.endswith("-radius"):
        return "0"
    if prop.endswith("-width"):
        return "0"
    if prop.endswith("-style"):
        return "none"
    if prop.endswith("-color"):
        return None
    if prop in ("left", "right"):
        return "auto"
    return "0"


def _parse_blocks(css: str, start: int = 0, end: int | None = None):
    """Yield (prelude, body, is_at_rule) for top-level blocks of ``css[start:end]``."""
    end = len(css) if end is None else end
    i = start
    while i < end:
        brace = css.find("{", i, end)
        if brace == -1:
            return
        # skip statements like @import ...; before the brace
        semi = css.rfind(";", i, brace)
        prelude_start = semi + 1 if semi != -1 else i
        prelude = css[prelude_start:brace].strip()
        depth = 1
        j = brace + 1
        while j < end and depth:
            if css[j] == "{":
                depth += 1
            elif css[j] == "}":
                depth -= 1
            j += 1
        yield prelude, css[brace + 1 : j - 1], prelude.startswith("@")
        i = j


def _rtl_selector(selector: str) -> str:
    return ",".join(f'[dir="rtl"] {part.strip()}' for part in selector.split(","))


def _collect(css: str, wrappers: tuple[str, ...], resets: list, sets: list) -> None:
    for prelude, body, is_at in _parse_blocks(css):
        if is_at:
            if prelude.startswith(("@layer", "@media", "@supports")):
                inner = wrappers if prelude.startswith("@layer") else (*wrappers, prelude)
                _collect(body, inner, resets, sets)
            continue
        if "{" in body or "dir(" in prelude or "rtl" in prelude or "ltr" in prelude:
            continue
        decls = _DECL_RE.findall(body)
        reset_decls, set_decls = [], []
        for prop, value in decls:
            if prop == "text-align" and value.strip() in ("left", "right"):
                set_decls.append(f"text-align:{'right' if value.strip() == 'left' else 'left'}")
                continue
            if prop == "float" and value.strip() in ("left", "right"):
                set_decls.append(f"float:{'right' if value.strip() == 'left' else 'left'}")
                continue
            if prop == "--tw-translate-x":
                set_decls.append(f"--tw-translate-x:calc(({value.strip()}) * -1)")
                continue
            if prop in SWAP_PROPS:
                reset = _reset_value(prop)
                if reset is not None:
                    reset_decls.append(f"{prop}:{reset}")
                set_decls.append(f"{SWAP_PROPS[prop]}:{value.strip()}")
        if not set_decls:
            continue
        selector = _rtl_selector(prelude)
        if reset_decls:
            resets.append((wrappers, f"{selector}{{{';'.join(reset_decls)}}}"))
        sets.append((wrappers, f"{selector}{{{';'.join(set_decls)}}}"))


def _wrap(wrappers: tuple[str, ...], rule: str) -> str:
    for w in reversed(wrappers):
        rule = f"{w}{{{rule}}}"
    return rule


def build_rtl_css(css: str) -> str:
    resets: list = []
    sets: list = []
    _collect(css, (), resets, sets)
    lines = [
        "/* Generated by `manage.py build_admin_rtl_css` from django-unfold "
        f"{version('django-unfold')}. Do not edit by hand. */",
        "/* 1) reset physical side, 2) apply it on the mirrored side */",
    ]
    lines += [_wrap(w, r) for w, r in resets]
    lines += [_wrap(w, r) for w, r in sets]
    return "\n".join(lines) + "\n"


class Command(BaseCommand):
    help = "Generate RTL overrides for django-unfold's physical (left/right) utilities."

    def handle(self, *args, **options):
        source = Path(unfold.__file__).parent / "static" / "unfold" / "css" / "styles.css"
        target = Path(settings.BASE_DIR) / "static" / "admin_theme" / "unfold-rtl.css"
        output = build_rtl_css(source.read_text(encoding="utf-8"))
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text(output, encoding="utf-8")
        self.stdout.write(self.style.SUCCESS(f"Wrote {target} ({output.count(chr(10))} rules)"))
