# Generated by Django 5.2.17 on 2026-10-02 15:56

from django.db import migrations, models


def create_singleton(apps, schema_editor):
    StoreSettings = apps.get_model("core", "StoreSettings")
    StoreSettings.objects.get_or_create(pk=1)


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StoreSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="سفارش\u200cهای بالاتر از این مبلغ ارسال رایگان دارند. ۰ یعنی ارسال رایگان نداریم.",
                        verbose_name="حد ارسال رایگان (تومان)",
                    ),
                ),
                (
                    "print_dispatch_note",
                    models.CharField(
                        default="ارسال حداکثر ۱ روز کاری پس از سفارش",
                        max_length=200,
                        verbose_name="متن زمان ارسال نسخه چاپی",
                    ),
                ),
                (
                    "delivery_tehran_note",
                    models.CharField(
                        default="تحویل تهران ۱ تا ۲ روز کاری",
                        max_length=200,
                        verbose_name="متن زمان تحویل تهران",
                    ),
                ),
                (
                    "delivery_province_note",
                    models.CharField(
                        default="سایر شهرها ۳ تا ۵ روز کاری",
                        max_length=200,
                        verbose_name="متن زمان تحویل سایر شهرها",
                    ),
                ),
                (
                    "consult_whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="شماره بین\u200cالمللی بدون + و صفر، مثلاً 989121234567. خالی یعنی دکمه نمایش داده نشود.",
                        max_length=20,
                        verbose_name="واتساپ مشاوره",
                    ),
                ),
                (
                    "consult_telegram",
                    models.CharField(
                        blank=True,
                        help_text="نام کاربری بدون @، مثلاً dadrose_support. خالی یعنی دکمه نمایش داده نشود.",
                        max_length=64,
                        verbose_name="تلگرام مشاوره",
                    ),
                ),
                (
                    "support_hours",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً «همه روزه ۹ تا ۲۱».",
                        max_length=100,
                        verbose_name="ساعات پاسخ\u200cگویی",
                    ),
                ),
                (
                    "enamad_html",
                    models.TextField(
                        blank=True,
                        help_text="کد <a><img> که اینماد می\u200cدهد. فقط تگ\u200cهای a و img نگه داشته می\u200cشوند.",
                        verbose_name="کد نماد اعتماد (اینماد)",
                    ),
                ),
                (
                    "students_count_claim",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً «+۱۵٬۰۰۰ دانشجوی آکادمی دادرُز». فقط با تأیید مالک پر شود؛ خالی یعنی نمایش داده نشود.",
                        max_length=100,
                        verbose_name="ادعای تعداد دانشجو",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات فروشگاه",
                "verbose_name_plural": "تنظیمات فروشگاه",
            },
        ),
        migrations.RunPython(create_singleton, migrations.RunPython.noop),
    ]
