# Generated by Django 5.2.17 on 2026-10-05 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="storesettings",
            name="low_stock_threshold",
            field=models.PositiveSmallIntegerField(
                default=3,
                help_text="نسخه\u200cهای چاپی با موجودی برابر یا کمتر از این عدد در پیشخوان هشدار می\u200cگیرند.",
                verbose_name="حد هشدار موجودی کم",
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="shipping_overdue_days",
            field=models.PositiveSmallIntegerField(
                default=10,
                help_text="سفارش ارسال\u200cشده\u200cای که بیش از این تعداد روز «تحویل\u200cشده» نشود در پیشخوان پیگیری می\u200cشود.",
                verbose_name="مهلت تحویل مرسوله (روز)",
            ),
        ),
    ]
