# Generated by Django 5.2.17 on 2026-10-05 14:46

from django.db import migrations, models


def seed_templates(apps, schema_editor):
    from apps.core.sms_catalog import KINDS

    SmsTemplate = apps.get_model("core", "SmsTemplate")
    for key, kind in KINDS.items():
        SmsTemplate.objects.get_or_create(key=key, defaults={"body": kind.default})


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_admin_dashboard_settings"),
    ]

    operations = [
        migrations.CreateModel(
            name="SmsTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        editable=False, max_length=40, unique=True, verbose_name="پیامک"
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="متغیرها را با آکولاد بنویسید، مثلاً {order}. فهرست متغیرهای مجاز زیر فرم آمده است.",
                        verbose_name="متن پیامک",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="اگر خاموش باشد این پیامک اصلاً فرستاده نمی\u200cشود.",
                        verbose_name="ارسال شود",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
            ],
            options={
                "verbose_name": "قالب پیامک",
                "verbose_name_plural": "قالب پیامک\u200cها",
                "ordering": ["id"],
            },
        ),
        migrations.AddField(
            model_name="storesettings",
            name="abandoned_cart_code",
            field=models.CharField(
                blank=True,
                help_text="اختیاری: کدی که در پیامک با متغیر {code} می\u200cآید. خود کد را در «کدهای تخفیف» بسازید.",
                max_length=40,
                verbose_name="کد تخفیف یادآوری",
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="abandoned_cart_enabled",
            field=models.BooleanField(
                default=False,
                help_text="به مشتریانی که وارد حساب شده\u200cاند و سبدشان را رها کرده\u200cاند یک پیامک یادآوری فرستاده می\u200cشود (هر سبد حداکثر یک بار). متن در «قالب پیامک\u200cها».",
                verbose_name="یادآوری سبد رهاشده",
            ),
        ),
        migrations.AddField(
            model_name="storesettings",
            name="abandoned_cart_hours",
            field=models.PositiveSmallIntegerField(
                default=6,
                help_text="سبدی که این مدت دست نخورده و به خرید نرسیده رهاشده حساب می\u200cشود.",
                verbose_name="فاصله یادآوری (ساعت)",
            ),
        ),
        migrations.RunPython(seed_templates, migrations.RunPython.noop),
    ]
