# Generated by Django 5.2.17 on 2026-10-02 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "placement",
                    models.CharField(
                        choices=[
                            ("HERO", "بنر اصلی (هیرو)"),
                            ("COURSE", "بنر کتاب + دوره"),
                        ],
                        default="HERO",
                        max_length=10,
                        verbose_name="جایگاه",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="banners/", verbose_name="تصویر"
                    ),
                ),
                (
                    "link_url",
                    models.CharField(
                        blank=True,
                        help_text="مسیر داخلی (مثل /kit) یا آدرس کامل.",
                        max_length=500,
                        verbose_name="لینک",
                    ),
                ),
                (
                    "link_label",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="متن دکمه"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "بنر",
                "verbose_name_plural": "بنرها",
                "ordering": ["placement", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="GuideVideo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("video_url", models.URLField(verbose_name="لینک ویدیو")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        upload_to="guide-videos/",
                        verbose_name="تصویر بندانگشتی",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "exam_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guide_videos",
                        to="catalog.examtype",
                        verbose_name="آزمون",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guide_videos",
                        to="catalog.subject",
                        verbose_name="درس",
                    ),
                ),
            ],
            options={
                "verbose_name": "ویدیوی راهنما",
                "verbose_name_plural": "ویدیوهای راهنما (کدام کتاب را بخوانم؟)",
                "ordering": ["order", "id"],
            },
        ),
    ]
