# Generated by Django 5.2.17 on 2026-10-05 16:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_hub_intro_fields"),
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CuratedList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="خالی بگذارید تا خودکار از عنوان ساخته شود.",
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="چرا این فهرست؟ برای ایندکس در گوگل حداقل حدود ۱۵۰ کلمه لازم است.",
                        verbose_name="مقدمه",
                    ),
                ),
                (
                    "ends_on",
                    models.DateField(
                        blank=True,
                        help_text="برای فهرست\u200cهای فصلی/کمپینی؛ پس از آن فهرست «پایان\u200cیافته» نمایش داده می\u200cشود.",
                        null=True,
                        verbose_name="تاریخ پایان",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
            ],
            options={
                "verbose_name": "فهرست پیشنهادی",
                "verbose_name_plural": "فهرست\u200cهای پیشنهادی",
                "ordering": ["order", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Guide",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="خالی بگذارید تا خودکار از عنوان ساخته شود.",
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                (
                    "summary",
                    models.CharField(
                        blank=True,
                        help_text="یک تا دو جمله؛ در نتایج گوگل و کارت راهنما نمایش داده می\u200cشود.",
                        max_length=300,
                        verbose_name="خلاصه",
                    ),
                ),
                (
                    "intro",
                    models.TextField(
                        blank=True,
                        help_text="بالای مقاله، پیش از متن اصلی.",
                        verbose_name="مقدمه",
                    ),
                ),
                ("body", models.TextField(verbose_name="متن اصلی")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "پیش\u200cنویس"), ("PUBLISHED", "منتشرشده")],
                        default="DRAFT",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "published_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="زمان انتشار",
                    ),
                ),
                (
                    "updated_on",
                    models.DateField(
                        blank=True,
                        help_text="آخرین بازبینی محتوایی (نه هر ویرایش جزئی)؛ به\u200cصورت «به\u200cروزشده در …» نمایش داده می\u200cشود.",
                        null=True,
                        verbose_name="تاریخ به\u200cروزرسانی محتوا",
                    ),
                ),
                (
                    "preview_key",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="کلید پیش\u200cنمایش",
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guides_written",
                        to="catalog.person",
                        verbose_name="نویسنده",
                    ),
                ),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guides",
                        to="catalog.book",
                        verbose_name="کتاب\u200cهای معرفی\u200cشده",
                    ),
                ),
                (
                    "exam_types",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guides",
                        to="catalog.examtype",
                        verbose_name="آزمون\u200cها",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="guides_reviewed",
                        to="catalog.person",
                        verbose_name="بازبین حقوقی",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="guides",
                        to="catalog.subject",
                        verbose_name="درس\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "راهنما (مقاله)",
                "verbose_name_plural": "راهنماها (مقاله)",
                "ordering": ["-updated_on", "-id"],
            },
        ),
        migrations.CreateModel(
            name="CuratedListItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True,
                        help_text="چرا این کتاب در فهرست است؟",
                        max_length=250,
                        verbose_name="یادداشت کوتاه",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_items",
                        to="catalog.book",
                        verbose_name="کتاب",
                    ),
                ),
                (
                    "curated_list",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="content.curatedlist",
                        verbose_name="فهرست",
                    ),
                ),
            ],
            options={
                "verbose_name": "کتاب فهرست",
                "verbose_name_plural": "کتاب\u200cهای فهرست",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("curated_list", "book"), name="unique_list_book"
                    )
                ],
            },
        ),
    ]
