# Generated by Django 5.2.17 on 2026-10-02 19:10

import apps.accounts.phone
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_book_course_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BackInStockRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        validators=[apps.accounts.phone.validate_phone],
                        verbose_name="موبایل",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("product", "صفحه محصول"),
                            ("card", "کارت کتاب"),
                            ("cart", "سبد خرید"),
                            ("kit", "بسته مطالعاتی"),
                        ],
                        max_length=20,
                        verbose_name="منبع",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "در انتظار"),
                            ("NOTIFIED", "اطلاع داده شد"),
                            ("CANCELLED", "لغو شده"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان اطلاع\u200cرسانی"
                    ),
                ),
                (
                    "converted_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان خرید"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="back_in_stock_requests",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="back_in_stock_requests",
                        to="catalog.bookvariant",
                        verbose_name="نسخه",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست اطلاع از موجودی",
                "verbose_name_plural": "درخواست\u200cهای اطلاع از موجودی",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["variant", "status"], name="bis_variant_status_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("status", "PENDING")),
                        fields=("variant", "phone"),
                        name="unique_pending_back_in_stock",
                    )
                ],
            },
        ),
    ]
