# Generated by Django 5.2.17 on 2026-10-05 16:52

import apps.growth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_book_course_links"),
        ("orders", "0003_returns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("STUDENT_ASSOCIATION", "انجمن دانشجویی"),
                            ("INSTITUTE", "مؤسسه"),
                            ("ACADEMY", "آکادمی / آموزشگاه"),
                            ("OTHER", "سایر"),
                        ],
                        max_length=24,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "contact_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام رابط"
                    ),
                ),
                (
                    "contact_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="تلفن رابط"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="یادداشت داخلی")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "همکار",
                "verbose_name_plural": "همکاران (کد همکاری)",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        max_length=160,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="زیرعنوان"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیح")),
                (
                    "hero_image",
                    models.ImageField(
                        blank=True,
                        upload_to="campaigns/",
                        verbose_name="تصویر بالای صفحه",
                    ),
                ),
                (
                    "hero_color",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً #12264A؛ خالی یعنی رنگ برند.",
                        max_length=7,
                        verbose_name="رنگ پس\u200cزمینه",
                    ),
                ),
                ("starts_at", models.DateTimeField(verbose_name="شروع")),
                ("ends_at", models.DateTimeField(verbose_name="پایان")),
                (
                    "show_on_home",
                    models.BooleanField(default=True, verbose_name="بنر صفحه اصلی"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True,
                        related_name="campaigns",
                        to="catalog.book",
                        verbose_name="کتاب\u200cهای مشمول",
                    ),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        blank=True,
                        help_text="یک کد تخفیف با متن غیرقابل\u200cحدس (مثلاً CAMP-…) بسازید؛ در بازه کمپین روی کتاب\u200cهای مشمول سبد خودکار اعمال می\u200cشود. درصد، سقف، حداقل سفارش و محدودیت هر کاربر از همان کد خوانده می\u200cشود.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="orders.discountcode",
                        verbose_name="قاعده تخفیف (خودکار)",
                    ),
                ),
                (
                    "exam_event",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="catalog.examevent",
                        verbose_name="تاریخ آزمون مرتبط",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="همه کتاب\u200cهای این درس\u200cها هم مشمول\u200cاند. اگر کتاب و درس هر دو خالی باشند، همه کتاب\u200cها مشمول\u200cاند.",
                        related_name="campaigns",
                        to="catalog.subject",
                        verbose_name="درس\u200cهای مشمول",
                    ),
                ),
            ],
            options={
                "verbose_name": "کمپین",
                "verbose_name_plural": "کمپین\u200cهای تقویم آزمون",
                "ordering": ["-starts_at"],
            },
        ),
        migrations.CreateModel(
            name="Gift",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        default=apps.growth.models.new_token,
                        max_length=40,
                        unique=True,
                        verbose_name="کد لینک",
                    ),
                ),
                (
                    "sender_name",
                    models.CharField(max_length=80, verbose_name="نام فرستنده"),
                ),
                (
                    "recipient_name",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="نام گیرنده"
                    ),
                ),
                (
                    "message",
                    models.CharField(blank=True, max_length=300, verbose_name="پیام"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "در انتظار پرداخت"),
                            ("ACTIVE", "آماده دریافت"),
                            ("CLAIMED", "دریافت\u200cشده"),
                            ("CANCELLED", "لغوشده"),
                        ],
                        db_index=True,
                        default="PENDING_PAYMENT",
                        max_length=16,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "activated_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="فعال\u200cشدن"
                    ),
                ),
                (
                    "expires_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="مهلت دریافت"
                    ),
                ),
                (
                    "claimed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان دریافت"
                    ),
                ),
                (
                    "shipping_address",
                    models.JSONField(
                        blank=True,
                        null=True,
                        verbose_name="نشانی گیرنده (ثبت\u200cشده)",
                    ),
                ),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_gifts",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="دریافت\u200cکننده",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gift",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "هدیه",
                "verbose_name_plural": "هدیه\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="KitShare",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "token",
                    models.CharField(
                        editable=False, max_length=16, unique=True, verbose_name="کد"
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        editable=False,
                        max_length=64,
                        unique=True,
                        verbose_name="اثر انگشت",
                    ),
                ),
                (
                    "variant_ids",
                    models.JSONField(default=list, verbose_name="نسخه\u200cها"),
                ),
                (
                    "views",
                    models.PositiveIntegerField(default=0, verbose_name="بازدید"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.examtype",
                        verbose_name="آزمون",
                    ),
                ),
            ],
            options={
                "verbose_name": "لینک اشتراک کیت",
                "verbose_name_plural": "لینک\u200cهای اشتراک کیت",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PartnerCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "discount_code",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="partner_link",
                        to="orders.discountcode",
                        verbose_name="کد تخفیف",
                    ),
                ),
                (
                    "partner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="codes",
                        to="growth.partner",
                        verbose_name="همکار",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد همکار",
                "verbose_name_plural": "کدهای همکار",
                "ordering": ["partner_id", "id"],
            },
        ),
    ]
