# Generated by Django 5.2.17 on 2026-10-02 19:04

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_book_course_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "code",
                    models.SlugField(
                        allow_unicode=True, unique=True, verbose_name="کد"
                    ),
                ),
                (
                    "description",
                    models.CharField(blank=True, max_length=250, verbose_name="توضیح"),
                ),
                (
                    "eta_note",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="زمان تحویل"
                    ),
                ),
                (
                    "base_price",
                    models.PositiveIntegerField(
                        default=0, verbose_name="هزینه (تومان)"
                    ),
                ),
                (
                    "free_over",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی یعنی از «حد ارسال رایگان» تنظیمات فروشگاه استفاده شود؛ ۰ یعنی همیشه رایگان.",
                        null=True,
                        verbose_name="رایگان برای سفارش\u200cهای بالای (تومان)",
                    ),
                ),
                (
                    "tehran_only",
                    models.BooleanField(
                        default=False,
                        help_text="مثلاً پیک؛ برای نشانی\u200cهای خارج از تهران نمایش داده نمی\u200cشود.",
                        verbose_name="فقط تهران",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
            ],
            options={
                "verbose_name": "روش ارسال",
                "verbose_name_plural": "روش\u200cهای ارسال",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="مثلاً «خانه»",
                        max_length=50,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "recipient_name",
                    models.CharField(max_length=150, verbose_name="نام گیرنده"),
                ),
                (
                    "recipient_phone",
                    models.CharField(max_length=11, verbose_name="موبایل گیرنده"),
                ),
                (
                    "province",
                    models.CharField(
                        choices=[
                            ("آذربایجان شرقی", "آذربایجان شرقی"),
                            ("آذربایجان غربی", "آذربایجان غربی"),
                            ("اردبیل", "اردبیل"),
                            ("اصفهان", "اصفهان"),
                            ("البرز", "البرز"),
                            ("ایلام", "ایلام"),
                            ("بوشهر", "بوشهر"),
                            ("تهران", "تهران"),
                            ("چهارمحال و بختیاری", "چهارمحال و بختیاری"),
                            ("خراسان جنوبی", "خراسان جنوبی"),
                            ("خراسان رضوی", "خراسان رضوی"),
                            ("خراسان شمالی", "خراسان شمالی"),
                            ("خوزستان", "خوزستان"),
                            ("زنجان", "زنجان"),
                            ("سمنان", "سمنان"),
                            ("سیستان و بلوچستان", "سیستان و بلوچستان"),
                            ("فارس", "فارس"),
                            ("قزوین", "قزوین"),
                            ("قم", "قم"),
                            ("کردستان", "کردستان"),
                            ("کرمان", "کرمان"),
                            ("کرمانشاه", "کرمانشاه"),
                            ("کهگیلویه و بویراحمد", "کهگیلویه و بویراحمد"),
                            ("گلستان", "گلستان"),
                            ("گیلان", "گیلان"),
                            ("لرستان", "لرستان"),
                            ("مازندران", "مازندران"),
                            ("مرکزی", "مرکزی"),
                            ("هرمزگان", "هرمزگان"),
                            ("همدان", "همدان"),
                            ("یزد", "یزد"),
                        ],
                        max_length=50,
                        verbose_name="استان",
                    ),
                ),
                ("city", models.CharField(max_length=80, verbose_name="شهر")),
                (
                    "postal_code",
                    models.CharField(
                        help_text="۱۰ رقم", max_length=10, verbose_name="کد پستی"
                    ),
                ),
                ("address_line", models.TextField(verbose_name="نشانی")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="پیش\u200cفرض"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "نشانی",
                "verbose_name_plural": "نشانی\u200cها",
                "ordering": ["-is_default", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscountCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="بدون فاصله؛ بزرگی و کوچکی حروف مهم نیست.",
                        max_length=40,
                        unique=True,
                        verbose_name="کد",
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="توضیح داخلی"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[("PERCENT", "درصدی"), ("FIXED", "مبلغ ثابت")],
                        default="PERCENT",
                        max_length=10,
                        verbose_name="نوع",
                    ),
                ),
                (
                    "value",
                    models.PositiveIntegerField(
                        help_text="درصد (۱ تا ۱۰۰) یا مبلغ ثابت به تومان.",
                        verbose_name="مقدار",
                    ),
                ),
                (
                    "max_discount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="فقط برای کد درصدی.",
                        null=True,
                        verbose_name="سقف تخفیف (تومان)",
                    ),
                ),
                (
                    "min_order_total",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="روی جمع اقلام مشمول حساب می\u200cشود.",
                        verbose_name="حداقل مبلغ سفارش (تومان)",
                    ),
                ),
                (
                    "max_uses",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی یعنی نامحدود.",
                        null=True,
                        verbose_name="حداکثر دفعات استفاده",
                    ),
                ),
                (
                    "per_user_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        default=1,
                        help_text="خالی یعنی نامحدود.",
                        null=True,
                        verbose_name="حداکثر استفاده هر کاربر",
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="شروع اعتبار"
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پایان اعتبار"
                    ),
                ),
                (
                    "formats",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='فهرست نوع نسخه\u200cها، مثلاً ["EBOOK"]؛ خالی یعنی همه.',
                        verbose_name="فقط برای نسخه\u200cها",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "used_count",
                    models.PositiveIntegerField(
                        default=0,
                        editable=False,
                        help_text="سفارش\u200cهای پرداخت\u200cشده.",
                        verbose_name="دفعات استفاده",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        help_text="خالی یعنی همه درس\u200cها.",
                        to="catalog.subject",
                        verbose_name="فقط برای درس\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف",
                "verbose_name_plural": "کدهای تخفیف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "number",
                    models.CharField(
                        editable=False,
                        max_length=20,
                        unique=True,
                        verbose_name="شماره سفارش",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING_PAYMENT", "در انتظار پرداخت"),
                            ("PAID", "پرداخت\u200cشده"),
                            ("PROCESSING", "در حال آماده\u200cسازی"),
                            ("SHIPPED", "ارسال\u200cشده"),
                            ("DELIVERED", "تحویل\u200cشده"),
                            ("CANCELLED", "لغوشده"),
                            ("FAILED", "پرداخت ناموفق"),
                        ],
                        db_index=True,
                        default="PENDING_PAYMENT",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "checkout_key",
                    models.UUIDField(
                        blank=True,
                        help_text="از فرانت\u200cاند می\u200cآید تا کلیک دوباره سفارش تکراری نسازد.",
                        null=True,
                        unique=True,
                        verbose_name="کلید یکتای تسویه",
                    ),
                ),
                (
                    "items_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="جمع اقلام (تومان)"
                    ),
                ),
                (
                    "discount_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تخفیف (تومان)"
                    ),
                ),
                (
                    "shipping_total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="هزینه ارسال (تومان)"
                    ),
                ),
                (
                    "total",
                    models.PositiveIntegerField(
                        default=0, verbose_name="مبلغ قابل پرداخت (تومان)"
                    ),
                ),
                (
                    "discount_code_text",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="کد تخفیف واردشده"
                    ),
                ),
                (
                    "needs_shipping",
                    models.BooleanField(default=False, verbose_name="نیاز به ارسال"),
                ),
                (
                    "shipping_method_name",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        verbose_name="روش ارسال (ثبت\u200cشده)",
                    ),
                ),
                (
                    "shipping_address",
                    models.JSONField(
                        blank=True, null=True, verbose_name="نشانی ارسال (ثبت\u200cشده)"
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True, max_length=60, verbose_name="کد رهگیری مرسوله"
                    ),
                ),
                (
                    "customer_note",
                    models.TextField(blank=True, verbose_name="یادداشت مشتری"),
                ),
                (
                    "staff_note",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان پرداخت"
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان ارسال"
                    ),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تحویل"
                    ),
                ),
                (
                    "cancelled_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان لغو"
                    ),
                ),
                (
                    "discount_code",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.discountcode",
                        verbose_name="کد تخفیف",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="مشتری",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="orders.shippingmethod",
                        verbose_name="روش ارسال",
                    ),
                ),
            ],
            options={
                "verbose_name": "سفارش",
                "verbose_name_plural": "سفارش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="DiscountRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "amount",
                    models.PositiveIntegerField(verbose_name="مبلغ تخفیف (تومان)"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "code",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemptions",
                        to="orders.discountcode",
                        verbose_name="کد",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="redemption",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "استفاده از کد تخفیف",
                "verbose_name_plural": "استفاده\u200cهای کد تخفیف",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=300, verbose_name="عنوان (ثبت\u200cشده)"
                    ),
                ),
                (
                    "variant_type",
                    models.CharField(max_length=10, verbose_name="نوع نسخه"),
                ),
                (
                    "list_price",
                    models.PositiveIntegerField(verbose_name="قیمت پشت جلد (تومان)"),
                ),
                (
                    "unit_price",
                    models.PositiveIntegerField(verbose_name="قیمت واحد (تومان)"),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name="تعداد",
                    ),
                ),
                ("line_total", models.PositiveIntegerField(verbose_name="جمع (تومان)")),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.book",
                        verbose_name="کتاب",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.bookvariant",
                        verbose_name="نسخه",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلم سفارش",
                "verbose_name_plural": "اقلام سفارش",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="از وضعیت"
                    ),
                ),
                ("to_status", models.CharField(max_length=20, verbose_name="به وضعیت")),
                (
                    "note",
                    models.CharField(blank=True, max_length=300, verbose_name="توضیح"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_logs",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "تغییر وضعیت سفارش",
                "verbose_name_plural": "تاریخچه وضعیت سفارش",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
