# Generated by Django 5.2.17 on 2026-10-05 14:50

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_seed_shipping_methods"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="refunded_total",
            field=models.PositiveIntegerField(
                default=0,
                editable=False,
                help_text="جمع استردادهای انجام\u200cشده (مرجوعی\u200cها)؛ درآمد خالص = مبلغ سفارش منهای این.",
                verbose_name="مبلغ مسترد شده (تومان)",
            ),
        ),
        migrations.CreateModel(
            name="ReturnRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "ثبت\u200cشده"),
                            ("APPROVED", "تأییدشده"),
                            ("RECEIVED", "کالا دریافت شد"),
                            ("REFUNDED", "وجه مسترد شد"),
                            ("REJECTED", "ردشده"),
                            ("CANCELLED", "لغوشده"),
                        ],
                        db_index=True,
                        default="REQUESTED",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DAMAGED", "آسیب\u200cدیده یا معیوب"),
                            ("WRONG_ITEM", "ارسال کالای اشتباه"),
                            ("CHANGED_MIND", "انصراف از خرید"),
                            ("LATE_DELIVERY", "تأخیر در تحویل"),
                            ("OTHER", "سایر"),
                        ],
                        max_length=20,
                        verbose_name="دلیل",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="توضیح دلیل"),
                ),
                (
                    "restock",
                    models.BooleanField(
                        default=True,
                        help_text="با «کالا دریافت شد» نسخه\u200cهای چاپی و پکیج به موجودی انبار برمی\u200cگردند.",
                        verbose_name="بازگشت به موجودی",
                    ),
                ),
                (
                    "revoke_ebook",
                    models.BooleanField(
                        default=False,
                        help_text="با استرداد وجه، دسترسی مشتری به کتاب\u200cهای الکترونیک این اقلام برداشته می\u200cشود.",
                        verbose_name="لغو دسترسی کتاب الکترونیک",
                    ),
                ),
                (
                    "refund_amount",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="خالی یعنی سهم اقلام مرجوعی از مبلغ سفارش؛ بیشتر از مبلغ قابل استرداد سفارش نمی\u200cشود.",
                        null=True,
                        verbose_name="مبلغ استرداد (تومان)",
                    ),
                ),
                (
                    "refund_method",
                    models.CharField(
                        choices=[
                            ("GATEWAY", "بازگشت از طریق درگاه"),
                            ("SHABA", "واریز به شبا"),
                            ("CARD", "واریز کارت\u200cبه\u200cکارت"),
                        ],
                        default="SHABA",
                        max_length=10,
                        verbose_name="روش استرداد",
                    ),
                ),
                (
                    "shaba",
                    models.CharField(
                        blank=True,
                        help_text="با IR و ۲۴ رقم، مثلاً IR06…",
                        max_length=26,
                        verbose_name="شماره شبا",
                    ),
                ),
                (
                    "card_number",
                    models.CharField(
                        blank=True, max_length=16, verbose_name="شماره کارت"
                    ),
                ),
                (
                    "account_holder",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="نام صاحب حساب"
                    ),
                ),
                (
                    "refund_reference",
                    models.CharField(
                        blank=True,
                        help_text="برای شبا و کارت پیش از «استرداد وجه» وارد شود.",
                        max_length=64,
                        verbose_name="شماره پیگیری واریز",
                    ),
                ),
                (
                    "staff_note",
                    models.TextField(blank=True, verbose_name="یادداشت داخلی"),
                ),
                (
                    "approved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید"
                    ),
                ),
                (
                    "received_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان دریافت کالا"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان استرداد"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان رد/لغو"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="ثبت\u200cکننده",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="returns",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "مرجوعی",
                "verbose_name_plural": "مرجوعی\u200cها و استرداد وجه",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReturnRequestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="از وضعیت"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="به وضعیت"
                    ),
                ),
                (
                    "note",
                    models.CharField(blank=True, max_length=500, verbose_name="توضیح"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="انجام\u200cدهنده",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="orders.returnrequest",
                        verbose_name="مرجوعی",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد مرجوعی",
                "verbose_name_plural": "تاریخچه مرجوعی",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="ReturnLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantity",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="تعداد",
                    ),
                ),
                (
                    "order_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="return_lines",
                        to="orders.orderitem",
                        verbose_name="قلم سفارش",
                    ),
                ),
                (
                    "return_request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="orders.returnrequest",
                        verbose_name="مرجوعی",
                    ),
                ),
            ],
            options={
                "verbose_name": "قلم مرجوعی",
                "verbose_name_plural": "اقلام مرجوعی",
                "ordering": ["id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("return_request", "order_item"),
                        name="one_line_per_item_per_return",
                    )
                ],
            },
        ),
    ]
