# Generated by Django 5.2.17 on 2026-10-05 16:50

import django.core.validators
from django.db import migrations, models


# Defaults matching the seeded texts: post «۳ تا ۵ روز کاری», courier «همان روز یا فردا».
DELIVERY_DAYS = {"post": (3, 5, 14), "courier": (0, 1, 12)}


def seed_delivery_days(apps, schema_editor):
    ShippingMethod = apps.get_model("orders", "ShippingMethod")
    for code, (low, high, cutoff) in DELIVERY_DAYS.items():
        ShippingMethod.objects.filter(code=code, min_business_days__isnull=True).update(
            min_business_days=low, max_business_days=high, cutoff_hour=cutoff
        )


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_returns"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingHoliday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True, verbose_name="تاریخ")),
                (
                    "title",
                    models.CharField(blank=True, max_length=100, verbose_name="مناسبت"),
                ),
            ],
            options={
                "verbose_name": "تعطیلی ارسال",
                "verbose_name_plural": "تعطیلات ارسال",
                "ordering": ["date"],
            },
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="cutoff_hour",
            field=models.PositiveSmallIntegerField(
                default=14,
                help_text="سفارش\u200cهایی که در روز کاری پیش از این ساعت (به وقت تهران) پرداخت شوند همان روز ارسال می\u200cشوند؛ بعد از آن از روز کاری بعد. جمعه و تعطیلات رسمی روز کاری نیستند.",
                validators=[django.core.validators.MaxValueValidator(23)],
                verbose_name="ساعت پایان ارسال همان روز",
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="max_business_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="خالی یعنی برابر حداقل.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(60)],
                verbose_name="حداکثر روز کاری تا تحویل",
            ),
        ),
        migrations.AddField(
            model_name="shippingmethod",
            name="min_business_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="از روز ارسال شمرده می\u200cشود؛ ۰ یعنی تحویل همان روز ارسال. خالی یعنی تاریخ تحویل تقریبی نمایش داده نشود.",
                null=True,
                validators=[django.core.validators.MaxValueValidator(60)],
                verbose_name="حداقل روز کاری تا تحویل",
            ),
        ),
        migrations.RunPython(seed_delivery_days, migrations.RunPython.noop),
    ]
