# Generated by Django 5.2.17 on 2026-10-05 21:01

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_book_course_links"),
        ("leads", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EditionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "upgrade_discount_percent",
                    models.PositiveSmallIntegerField(
                        default=40,
                        help_text="دارندگان ویرایش قبلی (خرید پرداخت\u200cشده یا دسترسی الکترونیک) این تخفیف را روی ویرایش جدید می\u200cگیرند.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(90),
                        ],
                        verbose_name="تخفیف ارتقا (درصد)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "notified_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="آخرین ارسال پیامک به دارندگان",
                    ),
                ),
                (
                    "new_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="older_edition_links",
                        to="catalog.book",
                        verbose_name="ویرایش جدید",
                    ),
                ),
                (
                    "old_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="newer_edition_links",
                        to="catalog.book",
                        verbose_name="ویرایش قبلی",
                    ),
                ),
            ],
            options={
                "verbose_name": "ارتقای ویرایش",
                "verbose_name_plural": "ارتقای ویرایش\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EditionUpgradeNotice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sent_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ارسال"),
                ),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notices",
                        to="study.editionlink",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیامک ارتقای ویرایش",
                "verbose_name_plural": "پیامک\u200cهای ارتقای ویرایش",
            },
        ),
        migrations.CreateModel(
            name="ReadingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="روز (تهران)")),
                (
                    "seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ثانیه\u200cها"
                    ),
                ),
                (
                    "goal_minutes",
                    models.PositiveSmallIntegerField(
                        verbose_name="هدف همان روز (دقیقه)"
                    ),
                ),
                (
                    "goal_met_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان رسیدن به هدف"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_days",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "روز مطالعه",
                "verbose_name_plural": "روزهای مطالعه",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ReadingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="شروع")),
                ("last_beat_at", models.DateTimeField(verbose_name="آخرین ضربان")),
                (
                    "seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ثانیه\u200cهای مطالعه فعال"
                    ),
                ),
                (
                    "start_page",
                    models.PositiveIntegerField(default=0, verbose_name="صفحه شروع"),
                ),
                (
                    "last_page",
                    models.PositiveIntegerField(default=0, verbose_name="آخرین صفحه"),
                ),
                (
                    "pages_read",
                    models.PositiveIntegerField(
                        default=0, verbose_name="صفحات پیش\u200cرفته"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "جلسه مطالعه",
                "verbose_name_plural": "جلسه\u200cهای مطالعه",
                "ordering": ["-last_beat_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewPrompt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("DELIVERED", "۱۰ روز پس از تحویل"),
                            ("READ", "۹۰٪ خوانده\u200cشده"),
                        ],
                        max_length=10,
                        verbose_name="دلیل",
                    ),
                ),
                (
                    "sms_sent_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="پیامک"),
                ),
                (
                    "dismissed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="بسته\u200cشده"
                    ),
                ),
                (
                    "answered_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="پاسخ داده\u200cشده"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_prompts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست نظر",
                "verbose_name_plural": "درخواست\u200cهای نظر",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "exam_name",
                    models.CharField(blank=True, max_length=200, verbose_name="آزمون"),
                ),
                (
                    "exam_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ آزمون"),
                ),
                (
                    "hours_per_day",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="ساعت در روز"
                    ),
                ),
                ("days", models.JSONField(default=list, verbose_name="روزهای مطالعه")),
                (
                    "review",
                    models.JSONField(default=list, verbose_name="روزهای جمع\u200cبندی"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "compressed_count",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="دفعات فشرده\u200cسازی"
                    ),
                ),
                (
                    "last_compressed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین فشرده\u200cسازی"
                    ),
                ),
                (
                    "lead",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="leads.lead",
                        verbose_name="سرنخ مبدأ",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_plans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "برنامه مطالعه کاربر",
                "verbose_name_plural": "برنامه\u200cهای مطالعه کاربران",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StudyPlanBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=300, verbose_name="نامک")),
                ("title", models.CharField(max_length=300, verbose_name="عنوان")),
                (
                    "subject",
                    models.JSONField(blank=True, null=True, verbose_name="درس"),
                ),
                ("total_pages", models.PositiveIntegerField(verbose_name="صفحات")),
                (
                    "pages_done",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تا صفحه (خوانده\u200cشده)"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="study.studyplan",
                    ),
                ),
            ],
            options={
                "verbose_name": "کتاب برنامه",
                "verbose_name_plural": "کتاب\u200cهای برنامه",
                "ordering": ["plan_id", "order", "id"],
            },
        ),
        migrations.CreateModel(
            name="StudyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "daily_goal_minutes",
                    models.PositiveSmallIntegerField(
                        default=20,
                        validators=[
                            django.core.validators.MinValueValidator(5),
                            django.core.validators.MaxValueValidator(600),
                        ],
                        verbose_name="هدف روزانه (دقیقه)",
                    ),
                ),
                (
                    "review_sms",
                    models.BooleanField(
                        default=True,
                        help_text="یک پیامک کوتاه برای نظر دادن درباره کتاب.",
                        verbose_name="پیامک درخواست نظر",
                    ),
                ),
                (
                    "last_beat_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین ضربان مطالعه"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات مطالعه",
                "verbose_name_plural": "تنظیمات مطالعه",
            },
        ),
        migrations.CreateModel(
            name="BookReadingDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="روز (تهران)")),
                (
                    "seconds",
                    models.PositiveIntegerField(
                        default=0, verbose_name="ثانیه\u200cها"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مطالعه روزانه کتاب",
                "verbose_name_plural": "مطالعه روزانه کتاب\u200cها",
                "indexes": [
                    models.Index(
                        fields=["user", "date"], name="study_bookr_user_id_027fbc_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "book", "date"), name="study_book_day_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="editionlink",
            constraint=models.UniqueConstraint(
                fields=("new_book", "old_book"), name="study_edition_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="editionlink",
            constraint=models.CheckConstraint(
                condition=models.Q(("new_book", models.F("old_book")), _negated=True),
                name="study_edition_not_self",
            ),
        ),
        migrations.AddConstraint(
            model_name="editionupgradenotice",
            constraint=models.UniqueConstraint(
                fields=("link", "user"), name="study_edition_notice_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="readingday",
            constraint=models.UniqueConstraint(
                fields=("user", "date"), name="study_day_unique"
            ),
        ),
        migrations.AddIndex(
            model_name="readingsession",
            index=models.Index(
                fields=["user", "book", "-last_beat_at"],
                name="study_readi_user_id_a55d1d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewprompt",
            constraint=models.UniqueConstraint(
                fields=("user", "book"), name="study_review_prompt_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="studyplanbook",
            constraint=models.UniqueConstraint(
                fields=("plan", "slug"), name="study_plan_book_unique"
            ),
        ),
    ]
