# Generated by Django 5.2.17 on 2026-10-02 14:58

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="خالی بگذارید تا خودکار از عنوان ساخته شود.",
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="عنوان")),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, max_length=250, verbose_name="زیرعنوان"
                    ),
                ),
                (
                    "edition",
                    models.CharField(blank=True, max_length=100, verbose_name="ویرایش"),
                ),
                (
                    "publish_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1300),
                            django.core.validators.MaxValueValidator(1500),
                        ],
                        verbose_name="سال انتشار (شمسی)",
                    ),
                ),
                (
                    "volumes",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="تعداد جلد"
                    ),
                ),
                (
                    "pages",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="تعداد صفحات"
                    ),
                ),
                (
                    "isbn",
                    models.CharField(blank=True, max_length=20, verbose_name="شابک"),
                ),
                ("description", models.TextField(blank=True, verbose_name="معرفی")),
                (
                    "table_of_contents",
                    models.TextField(
                        blank=True,
                        help_text="هر سرفصل در یک خط.",
                        verbose_name="فهرست مطالب",
                    ),
                ),
                (
                    "study_plan_note",
                    models.TextField(
                        blank=True, verbose_name="جایگاه در برنامه مطالعه"
                    ),
                ),
                (
                    "cover",
                    models.ImageField(
                        blank=True, upload_to="covers/", verbose_name="جلد"
                    ),
                ),
                (
                    "sample_pdf",
                    models.FileField(
                        blank=True, upload_to="samples/", verbose_name="نمونه PDF"
                    ),
                ),
                (
                    "intro_video_url",
                    models.URLField(blank=True, verbose_name="ویدیوی معرفی"),
                ),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="ویژه"),
                ),
                (
                    "is_quick_review",
                    models.BooleanField(default=False, verbose_name="سریع\u200cخوان"),
                ),
                (
                    "sales_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد فروش"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "search_text",
                    models.TextField(
                        blank=True, editable=False, verbose_name="متن جستجو"
                    ),
                ),
            ],
            options={
                "verbose_name": "کتاب",
                "verbose_name_plural": "کتاب\u200cها",
                "ordering": ["-sales_count", "id"],
            },
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="خالی بگذارید تا خودکار از عنوان ساخته شود.",
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "short_name",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="نام کوتاه"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "آزمون",
                "verbose_name_plural": "آزمون\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="خالی بگذارید تا خودکار از عنوان ساخته شود.",
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                ("bio", models.TextField(blank=True, verbose_name="زندگی\u200cنامه")),
                (
                    "photo",
                    models.ImageField(
                        blank=True, upload_to="people/", verbose_name="عکس"
                    ),
                ),
            ],
            options={
                "verbose_name": "شخص (نویسنده/مترجم)",
                "verbose_name_plural": "نویسندگان و مترجمان",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Publisher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="خالی بگذارید تا خودکار از عنوان ساخته شود.",
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                ("website", models.URLField(blank=True, verbose_name="وب\u200cسایت")),
            ],
            options={
                "verbose_name": "ناشر",
                "verbose_name_plural": "ناشران",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="RelatedCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("url", models.URLField(verbose_name="لینک دوره")),
                (
                    "price",
                    models.PositiveIntegerField(default=0, verbose_name="قیمت (تومان)"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, upload_to="courses/", verbose_name="تصویر"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
            ],
            options={
                "verbose_name": "دوره مرتبط",
                "verbose_name_plural": "دوره\u200cهای مرتبط",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="خالی بگذارید تا خودکار از عنوان ساخته شود.",
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="نام")),
                (
                    "color",
                    models.CharField(
                        default="#12264A",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#[0-9A-Fa-f]{6}$",
                                "رنگ را به شکل هگز وارد کنید، مثلاً #1F4E8C.",
                            )
                        ],
                        verbose_name="رنگ",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
            ],
            options={
                "verbose_name": "درس",
                "verbose_name_plural": "درس\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="BookSamplePage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="samples/pages/", verbose_name="تصویر صفحه"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sample_pages",
                        to="catalog.book",
                        verbose_name="کتاب",
                    ),
                ),
            ],
            options={
                "verbose_name": "صفحه نمونه",
                "verbose_name_plural": "صفحات نمونه (ورق بزنید)",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True,
                        blank=True,
                        help_text="خالی بگذارید تا خودکار از عنوان ساخته شود.",
                        max_length=200,
                        unique=True,
                        verbose_name="نامک",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="نام")),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("description", models.TextField(blank=True, verbose_name="توضیحات")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="catalog.category",
                        verbose_name="دسته والد",
                    ),
                ),
            ],
            options={
                "verbose_name": "دسته\u200cبندی",
                "verbose_name_plural": "دسته\u200cبندی\u200cها",
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                to="catalog.category",
                verbose_name="دسته\u200cبندی\u200cها",
            ),
        ),
        migrations.CreateModel(
            name="ExamEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="عنوان")),
                ("date", models.DateField(verbose_name="تاریخ برگزاری")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="catalog.examtype",
                        verbose_name="آزمون",
                    ),
                ),
            ],
            options={
                "verbose_name": "تاریخ آزمون",
                "verbose_name_plural": "تاریخ آزمون\u200cها",
                "ordering": ["date", "id"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="exam_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                to="catalog.examtype",
                verbose_name="آزمون\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="authors",
            field=models.ManyToManyField(
                blank=True,
                related_name="authored_books",
                to="catalog.person",
                verbose_name="نویسندگان",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="translators",
            field=models.ManyToManyField(
                blank=True,
                related_name="translated_books",
                to="catalog.person",
                verbose_name="مترجمان",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publisher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="books",
                to="catalog.publisher",
                verbose_name="ناشر",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="related_courses",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                to="catalog.relatedcourse",
                verbose_name="دوره\u200cهای مرتبط",
            ),
        ),
        migrations.CreateModel(
            name="StudyKitRecommendation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="یادداشت")),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "exam_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_recommendations",
                        to="catalog.examtype",
                        verbose_name="آزمون",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_recommendations",
                        to="catalog.subject",
                        verbose_name="درس",
                    ),
                ),
            ],
            options={
                "verbose_name": "بسته مطالعاتی پیشنهادی",
                "verbose_name_plural": "بسته\u200cهای مطالعاتی پیشنهادی",
                "ordering": ["exam_type__order", "subject__order", "id"],
            },
        ),
        migrations.AddField(
            model_name="book",
            name="subjects",
            field=models.ManyToManyField(
                blank=True,
                related_name="books",
                to="catalog.subject",
                verbose_name="درس\u200cها",
            ),
        ),
        migrations.CreateModel(
            name="BookVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("PRINT", "نسخه چاپی"),
                            ("EBOOK", "نسخه الکترونیک"),
                            ("BUNDLE", "چاپی + الکترونیک"),
                        ],
                        max_length=10,
                        verbose_name="نوع نسخه",
                    ),
                ),
                ("price", models.PositiveIntegerField(verbose_name="قیمت (تومان)")),
                (
                    "sale_price",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="قیمت با تخفیف (تومان)"
                    ),
                ),
                (
                    "stock",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="برای نسخه الکترونیک استفاده نمی\u200cشود.",
                        verbose_name="موجودی",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "price_is_placeholder",
                    models.BooleanField(
                        default=False,
                        help_text="قیمت هنوز توسط فروشگاه تأیید نشده است.",
                        verbose_name="قیمت موقت است",
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.book",
                        verbose_name="کتاب",
                    ),
                ),
            ],
            options={
                "verbose_name": "نسخه کتاب",
                "verbose_name_plural": "نسخه\u200cها و قیمت\u200cها",
                "ordering": ["book_id", "type"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book", "type"), name="unique_book_variant_type"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StudyKitItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "is_essential",
                    models.BooleanField(default=True, verbose_name="ضروری"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="kit_items",
                        to="catalog.book",
                        verbose_name="کتاب",
                    ),
                ),
                (
                    "recommendation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="catalog.studykitrecommendation",
                        verbose_name="بسته مطالعاتی",
                    ),
                ),
            ],
            options={
                "verbose_name": "کتاب بسته مطالعاتی",
                "verbose_name_plural": "کتاب\u200cهای بسته مطالعاتی",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recommendation", "book"), name="unique_kit_item_book"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="studykitrecommendation",
            constraint=models.UniqueConstraint(
                fields=("exam_type", "subject"), name="unique_kit_exam_type_subject"
            ),
        ),
    ]
