# Generated by Django 5.2.17 on 2026-10-02 15:56

from django.db import migrations, models


def quick_review_to_resource_type(apps, schema_editor):
    Book = apps.get_model("catalog", "Book")
    Book.objects.filter(is_quick_review=True).update(resource_type="QUICK_REVIEW")


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="law_updated_until",
            field=models.CharField(
                blank=True,
                help_text="مثلاً «اصلاحات قانون حمایت خانواده ۱۴۰۴». زیر نشان ویرایش نمایش داده می\u200cشود.",
                max_length=200,
                verbose_name="به\u200cروز تا (اصلاحات قانون)",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="resource_type",
            field=models.CharField(
                choices=[
                    ("TEXTBOOK", "درسنامه"),
                    ("TESTS", "تست و مجموعه سؤالات"),
                    ("LAWS", "مجموعه قوانین"),
                    ("QUICK_REVIEW", "سریع\u200cخوان"),
                    ("COURSE_NOTES", "جزوه دوره"),
                ],
                default="TEXTBOOK",
                help_text="«سریع\u200cخوان» با گزینه سریع\u200cخوان همگام می\u200cشود.",
                max_length=20,
                verbose_name="نوع منبع",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="season_sales_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="فعلاً دستی؛ از فاز ۳ از روی سفارش\u200cها خودکار پر می\u200cشود. فقط وقتی ۲۰ یا بیشتر باشد روی سایت نمایش داده می\u200cشود.",
                verbose_name="خریداران این فصل",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="study_days",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="حدود چند روز مطالعه لازم است؛ خالی یعنی نامشخص.",
                null=True,
                verbose_name="زمان مطالعه پیشنهادی (روز)",
            ),
        ),
        migrations.AddField(
            model_name="studykitrecommendation",
            name="weight",
            field=models.PositiveSmallIntegerField(
                blank=True,
                help_text="ضریب این درس در این آزمون؛ کاشی\u200cهای درس به ترتیب ضریب مرتب می\u200cشوند. ضرایب اولیه باید با دفترچه رسمی آزمون تطبیق داده شوند.",
                null=True,
                verbose_name="ضریب درس",
            ),
        ),
        migrations.RunPython(quick_review_to_resource_type, migrations.RunPython.noop),
    ]
