# Generated by Django 5.2.17 on 2026-10-02 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_research_quick_wins"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="cover_source_url",
            field=models.URLField(
                blank=True,
                help_text="تصویر جلد با دستور fetch_covers از این نشانی دریافت می\u200cشود (اگر جلد خالی باشد).",
                max_length=1000,
                verbose_name="نشانی منبع جلد",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="legacy_path",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="مسیر این کتاب در فروشگاه قبلی (مثلاً /product/…)؛ برای ریدایرکت ۳۰۱.",
                max_length=500,
                verbose_name="نشانی در سایت قبلی",
            ),
        ),
        migrations.AddField(
            model_name="bookvariant",
            name="price_note",
            field=models.CharField(
                blank=True,
                help_text="منبع/توضیح قیمت",
                max_length=250,
                verbose_name="منبع قیمت",
            ),
        ),
    ]
