# Generated by Django 5.2.17 on 2026-10-02 18:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_legacy_import_fields"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="relatedcourse",
            options={
                "ordering": ["order", "id"],
                "verbose_name": "دوره آکادمی",
                "verbose_name_plural": "دوره\u200cهای آکادمی",
            },
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="checked_on",
            field=models.DateField(blank=True, null=True, verbose_name="تاریخ بررسی"),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("FULL", "دوره جامع"),
                    ("ESSENTIALS", "امهات"),
                    ("TIPS_TESTS", "نکته و تست"),
                    ("REVIEW", "جمع\u200cبندی"),
                    ("WORKSHOP_ADVICE", "مشاوره و کارگاه"),
                    ("MOCK", "آزمون آزمایشی"),
                    ("PACKAGE", "پکیج"),
                    ("OTHER", "سایر"),
                ],
                default="OTHER",
                max_length=20,
                verbose_name="نوع دوره",
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="exam_types",
            field=models.ManyToManyField(
                blank=True,
                related_name="courses",
                to="catalog.examtype",
                verbose_name="آزمون\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=6,
                null=True,
                verbose_name="ساعت آموزش",
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="image_source_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="نشانی منبع تصویر"
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="intro_video_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="ویدیوی معرفی / جلسه رایگان"
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="is_free",
            field=models.BooleanField(default=False, verbose_name="رایگان"),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="is_module",
            field=models.BooleanField(
                default=False, verbose_name="بخشی از یک دوره بزرگ\u200cتر"
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="notes",
            field=models.TextField(blank=True, verbose_name="یادداشت داخلی"),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="rating",
            field=models.DecimalField(
                blank=True,
                decimal_places=1,
                max_digits=2,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="امتیاز",
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="reviews_count",
            field=models.PositiveIntegerField(default=0, verbose_name="تعداد نظرها"),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="sale_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="قیمت با تخفیف (تومان)"
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="selling_points",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="فهرست جمله\u200cهای کوتاه.",
                verbose_name="ویژگی\u200cها",
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="sessions",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="تعداد جلسات"
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="short_description",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="توضیح کوتاه"
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="source_url",
            field=models.URLField(
                blank=True, max_length=500, verbose_name="منبع اطلاعات"
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "قابل خرید"),
                    ("OPEN_UNLISTED", "قابل خرید (خارج از فهرست)"),
                    ("ARCHIVED", "بایگانی\u200cشده"),
                    ("LEGACY", "محصول قدیمی"),
                ],
                default="OPEN",
                help_text="فقط دوره\u200cهای «قابل خرید» روی سایت نمایش داده می\u200cشوند.",
                max_length=20,
                verbose_name="وضعیت",
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="students_count",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="تعداد دانشجو"
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="courses",
                to="catalog.subject",
                verbose_name="درس",
            ),
        ),
        migrations.AddField(
            model_name="relatedcourse",
            name="teachers",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text='فهرست نام\u200cها، مثلاً ["امین بیات"].',
                verbose_name="مدرسان",
            ),
        ),
        migrations.AlterField(
            model_name="relatedcourse",
            name="price",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="خالی یعنی قیمت نامعلوم (نمایش داده نمی\u200cشود).",
                null=True,
                verbose_name="قیمت (تومان)",
            ),
        ),
        migrations.AlterField(
            model_name="relatedcourse",
            name="title",
            field=models.CharField(max_length=250, verbose_name="عنوان"),
        ),
        migrations.AlterField(
            model_name="relatedcourse",
            name="url",
            field=models.URLField(
                max_length=500, unique=True, verbose_name="لینک دوره"
            ),
        ),
        migrations.CreateModel(
            name="SubjectCourseDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("code", models.CharField(max_length=50, verbose_name="کد تخفیف")),
                (
                    "percent",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="درصد تخفیف",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        blank=True,
                        help_text="خالی بگذارید تا خودکار ساخته شود، مثلاً «۱۵٪ تخفیف دوره\u200cهای حقوق مدنی برای خریداران این کتاب».",
                        max_length=200,
                        verbose_name="متن نمایشی",
                    ),
                ),
                (
                    "expires_on",
                    models.DateField(
                        blank=True,
                        help_text="خالی یعنی تا تاریخ آزمون بعدی نمایش داده می\u200cشود.",
                        null=True,
                        verbose_name="تاریخ انقضا",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_discounts",
                        to="catalog.subject",
                        verbose_name="درس",
                    ),
                ),
            ],
            options={
                "verbose_name": "کد تخفیف دوره",
                "verbose_name_plural": "کدهای تخفیف دوره",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="BookCourse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "relevance",
                    models.CharField(
                        choices=[
                            ("referenced", "تدریس\u200cشده بر اساس همین کتاب"),
                            ("same_author", "تدریس توسط مؤلف همین کتاب"),
                            ("same_subject", "دوره همین درس"),
                            ("general", "مهارت آزمون"),
                        ],
                        default="same_subject",
                        max_length=20,
                        verbose_name="نوع ارتباط",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="دلیل (داخلی)"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="course_links",
                        to="catalog.book",
                        verbose_name="کتاب",
                    ),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="book_links",
                        to="catalog.relatedcourse",
                        verbose_name="دوره",
                    ),
                ),
            ],
            options={
                "verbose_name": "دوره مرتبط با کتاب",
                "verbose_name_plural": "دوره\u200cهای مرتبط با کتاب",
                "ordering": ["order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("book", "course"), name="unique_book_course"
                    )
                ],
            },
        ),
    ]
