# Generated by Django 5.2.17 on 2026-10-05 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_book_course_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="examevent",
            name="registration_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="پایان ثبت\u200cنام"
            ),
        ),
        migrations.AddField(
            model_name="examevent",
            name="registration_start",
            field=models.DateField(
                blank=True, null=True, verbose_name="شروع ثبت\u200cنام"
            ),
        ),
    ]
