# Generated by Django 5.2.17 on 2026-10-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_book_course_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="examtype",
            name="intro",
            field=models.TextField(
                blank=True,
                help_text="متن اختصاصی صفحه این آزمون در سایت (حداقل حدود ۱۵۰ کلمه تا صفحه در گوگل ایندکس شود). HTML ساده مجاز است و پاک\u200cسازی می\u200cشود.",
                verbose_name="مقدمه صفحه",
            ),
        ),
        migrations.AddField(
            model_name="examtype",
            name="intro_byline",
            field=models.CharField(
                blank=True,
                help_text="مثلاً «تیم آموزشی آکادمی دادرُز»؛ زیر مقدمه نمایش داده می\u200cشود.",
                max_length=200,
                verbose_name="تهیه\u200cکننده مقدمه",
            ),
        ),
        migrations.AddField(
            model_name="examtype",
            name="intro_is_placeholder",
            field=models.BooleanField(
                default=False,
                help_text="متن نمونه\u200cای که هنوز آکادمی جایگزین نکرده؛ صفحه تا برداشتن این تیک noindex می\u200cماند.",
                verbose_name="مقدمه موقت است",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="affiliation",
            field=models.CharField(
                blank=True,
                help_text="مثلاً «دانشگاه تهران».",
                max_length=200,
                verbose_name="دانشگاه / سازمان",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="job_title",
            field=models.CharField(
                blank=True,
                help_text="مثلاً «عضو هیئت علمی دانشکده حقوق» یا «وکیل پایه یک».",
                max_length=200,
                verbose_name="سمت",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="same_as",
            field=models.TextField(
                blank=True,
                help_text="هر نشانی در یک خط (وب\u200cسایت شخصی، صفحه دانشگاه، ویکی\u200cپدیا…). فقط https.",
                verbose_name="صفحه\u200cهای رسمی",
            ),
        ),
        migrations.AddField(
            model_name="publisher",
            name="intro",
            field=models.TextField(
                blank=True,
                help_text="متن معرفی در صفحه ناشر. HTML ساده مجاز است و پاک\u200cسازی می\u200cشود.",
                verbose_name="معرفی ناشر",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="intro",
            field=models.TextField(
                blank=True,
                help_text="متن اختصاصی صفحه این درس در سایت (حداقل حدود ۱۵۰ کلمه تا صفحه در گوگل ایندکس شود). HTML ساده مجاز است و پاک\u200cسازی می\u200cشود.",
                verbose_name="مقدمه صفحه",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="intro_byline",
            field=models.CharField(
                blank=True,
                help_text="مثلاً «تیم آموزشی آکادمی دادرُز»؛ زیر مقدمه نمایش داده می\u200cشود.",
                max_length=200,
                verbose_name="تهیه\u200cکننده مقدمه",
            ),
        ),
        migrations.AddField(
            model_name="subject",
            name="intro_is_placeholder",
            field=models.BooleanField(
                default=False,
                help_text="متن نمونه\u200cای که هنوز آکادمی جایگزین نکرده؛ صفحه تا برداشتن این تیک noindex می\u200cماند.",
                verbose_name="مقدمه موقت است",
            ),
        ),
    ]
