# Generated by Django 5.2.17 on 2026-10-05 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_book_course_links"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="is_free_ebook",
            field=models.BooleanField(
                default=False,
                help_text="مثلاً متن قوانین. کاربر با «دریافت رایگان» (پس از ورود) آن را به کتابخانه\u200cاش اضافه می\u200cکند. فایل EPUB/PDF را در «فایل\u200cهای کتاب الکترونیک» بارگذاری کنید.",
                verbose_name="کتاب الکترونیک رایگان",
            ),
        ),
    ]
