# Generated by Django 5.2.17 on 2026-10-06 02:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0006_examevent_registration_window"),
        ("catalog", "0006_hub_intro_fields"),
    ]

    operations = []
