# Generated by Django 5.2.17 on 2026-10-06 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_book_is_free_ebook"),
        ("catalog", "0007_merge_hubs_registration_window"),
    ]

    operations = []
