# Generated by Django 5.2.17 on 2026-10-05 16:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyReminderConsent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sms",
                    models.BooleanField(
                        default=False, verbose_name="یادآور پیامکی مطالعه"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("payment_result", "صفحه شروع مطالعه"),
                            ("account", "حساب کاربری"),
                        ],
                        max_length=20,
                        verbose_name="محل ثبت",
                    ),
                ),
                (
                    "consented_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان موافقت"
                    ),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان انصراف"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_reminder_consent",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "رضایت یادآور مطالعه",
                "verbose_name_plural": "رضایت\u200cهای یادآور مطالعه",
                "ordering": ["-updated_at"],
            },
        ),
    ]
