# Generated by Django 5.2.17 on 2026-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="OtpCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="شماره موبایل"
                    ),
                ),
                ("code_hash", models.CharField(max_length=128, verbose_name="هش کد")),
                ("expires_at", models.DateTimeField(verbose_name="انقضا")),
                (
                    "attempts",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="تلاش\u200cهای ناموفق"
                    ),
                ),
                (
                    "consumed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="استفاده\u200cشده در"
                    ),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
            ],
            options={
                "verbose_name": "کد ورود",
                "verbose_name_plural": "کدهای ورود",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["phone", "-created_at"], name="otp_phone_created"
                    )
                ],
            },
        ),
    ]
