# Generated by Django 5.2.17 on 2026-10-05 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_book_course_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangelogEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                ("title", models.CharField(max_length=150, verbose_name="عنوان")),
                ("body", models.TextField(max_length=3000, verbose_name="توضیح")),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("reader", "کتابخوان"),
                            ("store", "فروشگاه"),
                            ("account", "حساب کاربری"),
                            ("fix", "رفع اشکال"),
                        ],
                        default="store",
                        max_length=20,
                        verbose_name="بخش",
                    ),
                ),
                (
                    "link",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="لینک (اختیاری)"
                    ),
                ),
                ("published_at", models.DateField(verbose_name="تاریخ انتشار")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="منتشرشده"),
                ),
                (
                    "announce",
                    models.BooleanField(
                        default=True,
                        help_text="یک بار برای کاربرانی که وارد شده\u200cاند نشان داده می\u200cشود.",
                        verbose_name="نمایش در پنجره «تازه\u200cها»",
                    ),
                ),
            ],
            options={
                "verbose_name": "تازه\u200cهای دادرُز",
                "verbose_name_plural": "تازه\u200cهای دادرُز (تغییرات)",
                "ordering": ["-published_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "muted_kinds",
                    models.JSONField(
                        blank=True, default=list, verbose_name="انواع خاموش\u200cشده"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "تنظیمات اعلان",
                "verbose_name_plural": "تنظیمات اعلان کاربران",
            },
        ),
        migrations.CreateModel(
            name="UserStudyProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "exam_year",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="مثلاً ۱۴۰۵",
                        null=True,
                        verbose_name="سال آزمون (شمسی)",
                    ),
                ),
                (
                    "exam_date",
                    models.DateField(blank=True, null=True, verbose_name="تاریخ آزمون"),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="تکمیل در"
                    ),
                ),
                (
                    "skipped_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="ردشده در"
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.examtype",
                        verbose_name="آزمون",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "weak_subjects",
                    models.ManyToManyField(
                        blank=True,
                        to="catalog.subject",
                        verbose_name="درس\u200cهایی که نیاز به تقویت دارند",
                    ),
                ),
            ],
            options={
                "verbose_name": "پروفایل مطالعه",
                "verbose_name_plural": "پروفایل\u200cهای مطالعه",
            },
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(db_index=True, max_length=40, verbose_name="نوع"),
                ),
                ("title", models.CharField(max_length=200, verbose_name="عنوان")),
                ("body", models.TextField(max_length=2000, verbose_name="متن")),
                (
                    "link",
                    models.CharField(
                        blank=True,
                        help_text="مسیر نسبی، مثلاً /account/orders",
                        max_length=500,
                        verbose_name="لینک داخل سایت",
                    ),
                ),
                (
                    "discount_code",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="کد تخفیف"
                    ),
                ),
                (
                    "read_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="خوانده\u200cشده در"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="ایجاد"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام کاربر",
                "verbose_name_plural": "پیام\u200cهای کاربران",
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(fields=["user", "read_at"], name="inbox_user_unread")
                ],
            },
        ),
    ]
