# Generated by Django 5.2.17 on 2026-10-02 18:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_book_course_links"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="موبایل"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[("study_plan", "برنامه مطالعه")],
                        default="study_plan",
                        max_length=30,
                        verbose_name="منبع",
                    ),
                ),
                (
                    "hours_per_day",
                    models.PositiveSmallIntegerField(
                        default=4, verbose_name="ساعت مطالعه در روز"
                    ),
                ),
                (
                    "consent",
                    models.BooleanField(
                        default=False, verbose_name="رضایت تماس و پیامک"
                    ),
                ),
                (
                    "token",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        unique=True,
                        verbose_name="توکن",
                    ),
                ),
                (
                    "plan",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        editable=False,
                        verbose_name="برنامه ساخته\u200cشده",
                    ),
                ),
                (
                    "ip_hash",
                    models.CharField(
                        blank=True, editable=False, max_length=64, verbose_name="هش IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(
                        blank=True,
                        editable=False,
                        max_length=200,
                        verbose_name="مرورگر",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="ایجاد"
                    ),
                ),
                (
                    "books",
                    models.ManyToManyField(
                        blank=True,
                        related_name="leads",
                        to="catalog.book",
                        verbose_name="کتاب\u200cها",
                    ),
                ),
                (
                    "exam_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="leads",
                        to="catalog.examtype",
                        verbose_name="آزمون",
                    ),
                ),
                (
                    "subjects",
                    models.ManyToManyField(
                        blank=True,
                        related_name="leads",
                        to="catalog.subject",
                        verbose_name="درس\u200cها",
                    ),
                ),
            ],
            options={
                "verbose_name": "سرنخ",
                "verbose_name_plural": "سرنخ\u200cها",
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
