# Generated by Django 5.2.17 on 2026-10-02 19:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_book_course_links"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Highlight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="صفحه",
                    ),
                ),
                ("text", models.TextField(max_length=2000, verbose_name="متن")),
                (
                    "note",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="یادداشت"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        choices=[
                            ("yellow", "زرد"),
                            ("green", "سبز"),
                            ("blue", "آبی"),
                            ("pink", "صورتی"),
                        ],
                        default="yellow",
                        max_length=10,
                        verbose_name="رنگ",
                    ),
                ),
                (
                    "rects",
                    models.JSONField(
                        blank=True, default=list, verbose_name="مستطیل\u200cها"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="موقعیت (EPUB)"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="highlights",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "هایلایت",
                "verbose_name_plural": "هایلایت\u200cها",
                "ordering": ["page", "created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "book", "page"],
                        name="reader_high_user_id_c517c1_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ReadingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="صفحه",
                    ),
                ),
                (
                    "total_pages",
                    models.PositiveIntegerField(default=0, verbose_name="کل صفحات"),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="موقعیت (EPUB)"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reading_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "پیشرفت مطالعه",
                "verbose_name_plural": "پیشرفت مطالعه",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "book"), name="reader_progress_user_book"
                    )
                ],
            },
        ),
    ]
