# Generated by Django 5.2.17 on 2026-10-05 09:13

import apps.core.storages
import apps.reader.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_book_course_links"),
        ("library", "0001_initial"),
        ("reader", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EpubPackage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="عنوان در فایل"
                    ),
                ),
                (
                    "language",
                    models.CharField(default="fa", max_length=20, verbose_name="زبان"),
                ),
                (
                    "direction",
                    models.CharField(default="rtl", max_length=3, verbose_name="جهت"),
                ),
                (
                    "total_pages",
                    models.PositiveIntegerField(default=0, verbose_name="صفحات مجازی"),
                ),
                (
                    "total_chars",
                    models.PositiveIntegerField(
                        default=0, verbose_name="تعداد نویسه\u200cها"
                    ),
                ),
                (
                    "toc",
                    models.JSONField(blank=True, default=list, verbose_name="فهرست"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان پردازش"),
                ),
                (
                    "ebook",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="epub_package",
                        to="library.ebookfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "بسته EPUB",
                "verbose_name_plural": "بسته\u200cهای EPUB",
            },
        ),
        migrations.CreateModel(
            name="ReaderDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, verbose_name="شناسه (هش)")),
                (
                    "label",
                    models.CharField(blank=True, max_length=100, verbose_name="دستگاه"),
                ),
                (
                    "first_seen",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="اولین استفاده"
                    ),
                ),
                ("last_seen", models.DateTimeField(verbose_name="آخرین استفاده")),
                (
                    "revoked_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="حذف\u200cشده در"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reader_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "دستگاه مطالعه",
                "verbose_name_plural": "دستگاه\u200cهای مطالعه",
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="ReaderAccessLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("open", "باز کردن کتاب"),
                            ("chapter", "دریافت فصل"),
                            ("file", "دریافت فایل"),
                            ("asset", "دریافت تصویر"),
                            ("search", "جستجو"),
                            ("denied", "رد دسترسی"),
                        ],
                        max_length=10,
                        verbose_name="رویداد",
                    ),
                ),
                (
                    "detail",
                    models.CharField(blank=True, max_length=200, verbose_name="جزئیات"),
                ),
                (
                    "ip",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP"
                    ),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=255, verbose_name="مرورگر"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="زمان"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reader_access_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="reader.readerdevice",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش دسترسی کتابخوان",
                "verbose_name_plural": "گزارش دسترسی کتابخوان",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)],
                        verbose_name="صفحه",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="موقعیت (EPUB)"
                    ),
                ),
                (
                    "label",
                    models.CharField(blank=True, max_length=120, verbose_name="برچسب"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bookmarks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "نشانک",
                "verbose_name_plural": "نشانک\u200cها",
                "ordering": ["page", "created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "book", "page", "location"),
                        name="reader_bookmark_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EpubChapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("index", models.PositiveIntegerField(verbose_name="ترتیب")),
                ("href", models.CharField(max_length=500, verbose_name="مسیر در فایل")),
                (
                    "title",
                    models.CharField(blank=True, max_length=300, verbose_name="عنوان"),
                ),
                ("html", models.TextField(verbose_name="HTML پاک\u200cسازی\u200cشده")),
                ("text", models.TextField(verbose_name="متن ساده")),
                (
                    "chars",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نویسه\u200cها"
                    ),
                ),
                (
                    "start_page",
                    models.PositiveIntegerField(default=1, verbose_name="صفحه شروع"),
                ),
                ("pages", models.PositiveIntegerField(default=1, verbose_name="صفحات")),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chapters",
                        to="reader.epubpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "فصل EPUB",
                "verbose_name_plural": "فصل\u200cهای EPUB",
                "ordering": ["package_id", "index"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("package", "index"), name="reader_epub_chapter_index"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EpubAsset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=500, verbose_name="مسیر در فایل")),
                ("media_type", models.CharField(max_length=100, verbose_name="نوع")),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        storage=apps.core.storages.private_storage,
                        upload_to=apps.reader.models.epub_asset_upload_to,
                        verbose_name="فایل",
                    ),
                ),
                (
                    "package",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="reader.epubpackage",
                    ),
                ),
            ],
            options={
                "verbose_name": "تصویر EPUB",
                "verbose_name_plural": "تصاویر EPUB",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("package", "path"), name="reader_epub_asset_path"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="readerdevice",
            constraint=models.UniqueConstraint(
                fields=("user", "key"), name="reader_device_user_key"
            ),
        ),
        migrations.AddIndex(
            model_name="readeraccesslog",
            index=models.Index(
                fields=["user", "created_at"], name="reader_read_user_id_4407b3_idx"
            ),
        ),
    ]
