# Generated by Django 5.2.17 on 2026-10-05 14:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_book_course_links"),
        ("reader", "0002_epub_bookmarks_devices"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="readeraccesslog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("open", "باز کردن کتاب"),
                    ("chapter", "دریافت فصل"),
                    ("file", "دریافت فایل"),
                    ("asset", "دریافت تصویر"),
                    ("search", "جستجو"),
                    ("export", "خروجی یادداشت\u200cها"),
                    ("offline", "بسته آفلاین"),
                    ("denied", "رد دسترسی"),
                ],
                max_length=10,
                verbose_name="رویداد",
            ),
        ),
        migrations.CreateModel(
            name="CopyLedger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used",
                    models.PositiveIntegerField(
                        default=0, verbose_name="نویسه\u200cهای کپی\u200cشده"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="copy_ledgers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "سهمیه کپی",
                "verbose_name_plural": "سهمیه\u200cهای کپی",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "book"), name="reader_copy_user_book"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OfflineLicense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("expires_at", models.DateTimeField(verbose_name="انقضا")),
                (
                    "revoked_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="لغو"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="reader.readerdevice",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="offline_licenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "مجوز مطالعه آفلاین",
                "verbose_name_plural": "مجوزهای مطالعه آفلاین",
                "ordering": ["-created_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "book", "device"),
                        name="reader_offline_user_book_device",
                    )
                ],
            },
        ),
    ]
