# Generated by Django 5.2.17 on 2026-10-05 16:50

import apps.core.storages
import apps.reader.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_book_is_free_ebook"),
        ("library", "0002_free_source_and_sample"),
        ("reader", "0003_copy_quota_offline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="bookmark",
            name="anchor_status",
            field=models.CharField(
                choices=[
                    ("anchored", "در جای خود"),
                    ("orphaned", "جابه\u200cجا شده (در نسخه جدید پیدا نشد)"),
                ],
                default="anchored",
                max_length=10,
                verbose_name="وضعیت جایابی",
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="context_after",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="متن پس از آن"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="context_before",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="متن پیش از آن"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="ebook_version",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="نسخه فایل"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="previous_page",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="صفحه در نسخه قبلی"
            ),
        ),
        migrations.AddField(
            model_name="bookmark",
            name="reanchored_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="جایابی دوباره"
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="anchor_status",
            field=models.CharField(
                choices=[
                    ("anchored", "در جای خود"),
                    ("orphaned", "جابه\u200cجا شده (در نسخه جدید پیدا نشد)"),
                ],
                default="anchored",
                max_length=10,
                verbose_name="وضعیت جایابی",
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="context_after",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="متن پس از آن"
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="context_before",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="متن پیش از آن"
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="ebook_version",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="نسخه فایل"
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="previous_page",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="صفحه در نسخه قبلی"
            ),
        ),
        migrations.AddField(
            model_name="highlight",
            name="reanchored_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="جایابی دوباره"
            ),
        ),
        migrations.AddField(
            model_name="readingprogress",
            name="context_after",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="متن پس از موقعیت"
            ),
        ),
        migrations.AddField(
            model_name="readingprogress",
            name="ebook_version",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="نسخه فایل"
            ),
        ),
        migrations.CreateModel(
            name="PdfSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages", models.PositiveIntegerField(verbose_name="صفحات نمونه")),
                (
                    "total_pages",
                    models.PositiveIntegerField(default=0, verbose_name="صفحات کتاب"),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=300,
                        storage=apps.core.storages.private_storage,
                        upload_to=apps.reader.models.sample_upload_to,
                        verbose_name="فایل نمونه",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان ساخت"),
                ),
                (
                    "ebook",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_sample",
                        to="library.ebookfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "نمونه PDF کتاب\u200cخوان",
                "verbose_name_plural": "نمونه\u200cهای PDF کتاب\u200cخوان",
            },
        ),
        migrations.CreateModel(
            name="PdfTextIndex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pages", models.JSONField(default=list, verbose_name="متن صفحات")),
                (
                    "page_count",
                    models.PositiveIntegerField(default=0, verbose_name="تعداد صفحات"),
                ),
                ("ok", models.BooleanField(default=False, verbose_name="استخراج موفق")),
                (
                    "error",
                    models.CharField(blank=True, max_length=200, verbose_name="خطا"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="زمان"),
                ),
                (
                    "ebook",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pdf_text_index",
                        to="library.ebookfile",
                    ),
                ),
            ],
            options={
                "verbose_name": "متن صفحات PDF",
                "verbose_name_plural": "متن صفحات PDF",
            },
        ),
        migrations.CreateModel(
            name="ProblemReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "ebook_version",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="نسخه فایل"
                    ),
                ),
                (
                    "ebook_format",
                    models.CharField(blank=True, max_length=10, verbose_name="قالب"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("typo", "غلط تایپی یا محتوایی"),
                            ("missing_page", "صفحه یا بخش ناقص"),
                            ("display", "مشکل نمایش"),
                            ("other", "سایر"),
                        ],
                        max_length=20,
                        verbose_name="نوع مشکل",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, max_length=2000, verbose_name="توضیح"),
                ),
                (
                    "page",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="صفحه"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="موقعیت (EPUB)"
                    ),
                ),
                (
                    "chapter_title",
                    models.CharField(blank=True, max_length=300, verbose_name="فصل"),
                ),
                (
                    "device_label",
                    models.CharField(blank=True, max_length=100, verbose_name="دستگاه"),
                ),
                (
                    "user_agent",
                    models.CharField(blank=True, max_length=255, verbose_name="مرورگر"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "جدید"),
                            ("in_progress", "در حال بررسی"),
                            ("resolved", "رسیدگی\u200cشده"),
                            ("rejected", "بدون نیاز به اقدام"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=20,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "staff_note",
                    models.TextField(blank=True, verbose_name="یادداشت پشتیبانی"),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان رسیدگی"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                        verbose_name="کتاب",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reader_problem_reports",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "گزارش مشکل کتاب",
                "verbose_name_plural": "گزارش\u200cهای مشکل کتاب",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StatuteLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "chapter_index",
                    models.PositiveIntegerField(
                        help_text="ترتیب فصل در فایل، از صفر (فهرست فصل\u200cها در بسته EPUB).",
                        verbose_name="شماره فصل (EPUB)",
                    ),
                ),
                (
                    "anchor",
                    models.CharField(
                        blank=True,
                        help_text="id عنصر ماده در فایل (مثلاً m10). خالی یعنی کل فصل.",
                        max_length=200,
                        verbose_name="شناسه ماده",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="مثلاً «ماده ۱۰»",
                        max_length=120,
                        verbose_name="عنوان",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="ترتیب"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="فعال")),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="statute_links",
                        to="catalog.book",
                        verbose_name="کتاب قانون",
                    ),
                ),
                (
                    "target_book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                        verbose_name="کتاب شرح (پولی)",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیوند ماده به کتاب شرح",
                "verbose_name_plural": "پیوندهای ماده به کتاب شرح",
                "ordering": ["book_id", "chapter_index", "order", "id"],
            },
        ),
    ]
