# Generated by Django 5.2.17 on 2026-10-06 08:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_book_course_links"),
        ("reader", "0003_copy_quota_offline"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="readeraccesslog",
            name="kind",
            field=models.CharField(
                choices=[
                    ("open", "باز کردن کتاب"),
                    ("chapter", "دریافت فصل"),
                    ("file", "دریافت فایل"),
                    ("asset", "دریافت تصویر"),
                    ("search", "جستجو"),
                    ("export", "خروجی یادداشت\u200cها"),
                    ("offline", "بسته آفلاین"),
                    ("capture", "تلاش برای اسکرین\u200cشات"),
                    ("denied", "رد دسترسی"),
                ],
                max_length=10,
                verbose_name="رویداد",
            ),
        ),
        migrations.CreateModel(
            name="ReaderTraceCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        max_length=9, unique=True, verbose_name="کد ردیابی"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "book",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.book",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reader_trace_codes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "کد ردیابی اسکرین\u200cشات",
                "verbose_name_plural": "کدهای ردیابی اسکرین\u200cشات",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "book"), name="reader_trace_user_book"
                    )
                ],
            },
        ),
    ]
