# Generated by Django 5.2.17 on 2026-10-02 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("gateway", models.CharField(max_length=30, verbose_name="درگاه")),
                (
                    "amount_rial",
                    models.PositiveBigIntegerField(verbose_name="مبلغ (ریال)"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("INITIATED", "ایجادشده"),
                            ("REDIRECTED", "ارسال به درگاه"),
                            ("PAID", "موفق"),
                            ("FAILED", "ناموفق"),
                            ("CANCELLED", "انصراف کاربر"),
                        ],
                        db_index=True,
                        default="INITIATED",
                        max_length=12,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "authority",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        unique=True,
                        verbose_name="شناسه درگاه (Authority)",
                    ),
                ),
                (
                    "ref_id",
                    models.CharField(
                        blank=True, max_length=64, verbose_name="کد پیگیری بانک"
                    ),
                ),
                (
                    "card_pan",
                    models.CharField(
                        blank=True, max_length=32, verbose_name="کارت (ماسک\u200cشده)"
                    ),
                ),
                (
                    "raw_request",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ درخواست"
                    ),
                ),
                (
                    "raw_verify",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="پاسخ تأیید"
                    ),
                ),
                (
                    "error",
                    models.CharField(blank=True, max_length=300, verbose_name="خطا"),
                ),
                (
                    "verified_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="زمان تأیید"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
            ],
            options={
                "verbose_name": "پرداخت",
                "verbose_name_plural": "پرداخت\u200cها",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PaymentLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event", models.CharField(max_length=40, verbose_name="رویداد")),
                (
                    "from_status",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="از وضعیت"
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        blank=True, max_length=12, verbose_name="به وضعیت"
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="داده"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "payment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="payments.payment",
                        verbose_name="پرداخت",
                    ),
                ),
            ],
            options={
                "verbose_name": "رویداد پرداخت",
                "verbose_name_plural": "رویدادهای پرداخت",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "PAID")),
                fields=("order",),
                name="one_paid_payment_per_order",
            ),
        ),
    ]
