# Generated by Django 5.2.17 on 2026-10-05 21:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0005_book_course_links"),
        ("orders", "0003_returns"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "tracking_code",
                    models.CharField(
                        editable=False,
                        max_length=12,
                        unique=True,
                        verbose_name="کد پیگیری",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        db_index=True, max_length=11, verbose_name="شماره موبایل"
                    ),
                ),
                (
                    "name",
                    models.CharField(blank=True, max_length=100, verbose_name="نام"),
                ),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("order", "پیگیری سفارش و ارسال"),
                            ("ebook", "کتاب الکترونیک و کتابخوان"),
                            ("payment", "پرداخت"),
                            ("return", "بازگشت کالا و استرداد"),
                            ("account", "ورود و حساب کاربری"),
                            ("book", "پرسش درباره کتاب و انتخاب منبع"),
                            ("other", "سایر موارد"),
                        ],
                        max_length=20,
                        verbose_name="موضوع",
                    ),
                ),
                ("subject", models.CharField(max_length=150, verbose_name="عنوان")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "در انتظار پاسخ"),
                            ("answered", "پاسخ داده شد"),
                            ("closed", "بسته شد"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=10,
                        verbose_name="وضعیت",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True, max_length=40, verbose_name="صفحه ثبت"
                    ),
                ),
                (
                    "last_customer_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین پیام مشتری"
                    ),
                ),
                (
                    "last_staff_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="آخرین پاسخ پشتیبانی"
                    ),
                ),
                (
                    "closed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="بسته\u200cشده در"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="catalog.book",
                        verbose_name="کتاب",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="orders.order",
                        verbose_name="سفارش",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="support_tickets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کاربر",
                    ),
                ),
            ],
            options={
                "verbose_name": "درخواست پشتیبانی",
                "verbose_name_plural": "درخواست\u200cهای پشتیبانی",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        choices=[("customer", "مشتری"), ("staff", "پشتیبانی دادرُز")],
                        max_length=10,
                        verbose_name="نویسنده",
                    ),
                ),
                ("body", models.TextField(max_length=4000, verbose_name="متن")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="زمان"),
                ),
                (
                    "staff_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="کارمند",
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "verbose_name": "پیام درخواست",
                "verbose_name_plural": "پیام\u200cهای درخواست",
                "ordering": ["created_at", "id"],
            },
        ),
    ]
