# Generated by Django 5.2.17 on 2026-10-02 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NotFoundHit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "path",
                    models.CharField(max_length=500, unique=True, verbose_name="مسیر"),
                ),
                (
                    "path_key",
                    models.CharField(
                        editable=False,
                        max_length=500,
                        unique=True,
                        verbose_name="کلید جستجو",
                    ),
                ),
                ("hits", models.PositiveIntegerField(default=0, verbose_name="تعداد")),
                (
                    "first_seen",
                    models.DateTimeField(auto_now_add=True, verbose_name="اولین بار"),
                ),
                (
                    "last_seen",
                    models.DateTimeField(auto_now=True, verbose_name="آخرین بار"),
                ),
                (
                    "last_referer",
                    models.CharField(
                        blank=True,
                        max_length=500,
                        verbose_name="آخرین ارجاع\u200cدهنده",
                    ),
                ),
                (
                    "resolved",
                    models.BooleanField(default=False, verbose_name="رسیدگی شد"),
                ),
            ],
            options={
                "verbose_name": "صفحه پیدانشده (۴۰۴)",
                "verbose_name_plural": "صفحه\u200cهای پیدانشده (۴۰۴)",
                "ordering": ["-hits", "-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="Redirect",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="ایجاد"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="به\u200cروزرسانی"
                    ),
                ),
                (
                    "old_path",
                    models.CharField(
                        help_text="مسیر در سایت قبلی، مثلاً /product/حقوق-مدنی یا نشانی کامل؛ حروف فارسی و کدشده (%D8…) هر دو قبول است.",
                        max_length=500,
                        unique=True,
                        verbose_name="نشانی قدیمی",
                    ),
                ),
                (
                    "old_path_key",
                    models.CharField(
                        db_index=True,
                        editable=False,
                        max_length=500,
                        unique=True,
                        verbose_name="کلید جستجو",
                    ),
                ),
                (
                    "new_path",
                    models.CharField(
                        help_text="مسیر داخلی که با / شروع می\u200cشود (مثلاً /product/…) یا نشانی کامل https://…",
                        max_length=500,
                        verbose_name="نشانی جدید",
                    ),
                ),
                (
                    "status_code",
                    models.PositiveSmallIntegerField(
                        choices=[(301, "۳۰۱ — دائمی"), (302, "۳۰۲ — موقت")],
                        default=301,
                        verbose_name="نوع ریدایرکت",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="ریدایرکت\u200cهای پیش\u200cفرض را به\u200cجای حذف غیرفعال کنید؛ حذف\u200cشده\u200cها با اجرای دوباره seed ساخته می\u200cشوند.",
                        verbose_name="فعال",
                    ),
                ),
                (
                    "hit_count",
                    models.PositiveIntegerField(
                        default=0, editable=False, verbose_name="تعداد بازدید"
                    ),
                ),
                (
                    "last_hit_at",
                    models.DateTimeField(
                        blank=True,
                        editable=False,
                        null=True,
                        verbose_name="آخرین بازدید",
                    ),
                ),
                ("note", models.TextField(blank=True, verbose_name="یادداشت")),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("SEED", "پیش\u200cفرض سازیتو"),
                            ("ADMIN", "دستی"),
                            ("IMPORT", "درون\u200cریزی CSV"),
                            ("NOT_FOUND", "از گزارش ۴۰۴"),
                        ],
                        default="ADMIN",
                        max_length=10,
                        verbose_name="منبع",
                    ),
                ),
            ],
            options={
                "verbose_name": "ریدایرکت",
                "verbose_name_plural": "ریدایرکت\u200cها",
                "ordering": ["old_path"],
            },
        ),
    ]
